services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: stationary_app
    volumes:
      - .:/var/www
    networks:
      - stationary_network
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: stationary_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - stationary_network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: stationary_mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - stationary_network

  npm:
    image: node:20
    container_name: stationary_npm
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "npm install && npm run dev"
    networks:
      - stationary_network
    depends_on:
      - app

volumes:
  mysql_data:

networks:
  stationary_network:
    driver: bridge
